apiVersion: v1
kind: Service
metadata:
  name: open-webui-nodeport
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: nodeport-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30401
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
