apiVersion: v1
kind: Service
metadata:
  name: litellm-nodeport
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: litellm
    app.kubernetes.io/component: nodeport-service
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30400
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: litellm
