
ollama:
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  enabled: false

pipelines:
  # -- Automatically install Pipelines chart to extend Open WebUI functionality using Pipelines: https://github.com/open-webui/pipelines
  enabled: false

enableOpenaiApi: false

extraEnvVars: 
  - name: ENABLE_FORWARD_USER_INFO_HEADERS
    value: "true"
  - name: OPENID_PROVIDER_URL
    value: "https://accounts.google.com/.well-known/openid-configuration"

extraEnvFrom:
  - secretRef:
      name: postgres-credentials

sso:
  enabled: true
  enableSignup: true

  google:
    enabled: true
    clientId: "241824255096-g52vq0gh29q4qba5rupvmqvt8rmjhj5m.apps.googleusercontent.com"
    clientExistingSecret: "google-oauth-secret"
    clientExistingSecretKey: "client_secret"